<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
  </PropertyGroup>
  <!--Package versions-->
  <PropertyGroup>
    <Foob4eb9572PackageVersion>1.1.0</Foob4eb9572PackageVersion>
    <Barb4eb9572PackageVersion>2.1.0</Barb4eb9572PackageVersion>
    <Pinnedb4eb9572PackageVersion>2.1.0</Pinnedb4eb9572PackageVersion>
  </PropertyGroup>
</Project>
