<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
  </PropertyGroup>
  <!--Package versions-->
  <PropertyGroup>
    <Foo577db8a5PackageVersion>1.1.0</Foo577db8a5PackageVersion>
    <Bar577db8a5PackageVersion>2.1.0</Bar577db8a5PackageVersion>
    <Pinned577db8a5PackageVersion>2.1.0</Pinned577db8a5PackageVersion>
  </PropertyGroup>
</Project>
